language: elixir
elixir:
  - 1.4
  - 1.5
  - 1.6
otp_release:
  - 18.3
  - 19.3
  - 20.3
env:
  - MIX_ENV=test
script:
  - mix test
  - mix credo --strict
  - mix coveralls.travis
  - if [[ `elixir -v` = *"1.6"* ]]; then mix format --check-formatted --dry-run; fi
